{
  "outbounds": [
    {
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "141.227.178.242",
            "port": 29803,
            "users": [
              {
                "id": "aa4f8c93-e4ec-48fe-8043-2f8e4f1c006d",
                "alterId": 0,
                "security": "none",
                "encryption": "none"
              }
            ]
          }
        ],
        "serviceName": "ZEDMODEON-ZEDMODEON-bia-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON",
        "authority": "/napsternet25eoekepsosowowp",
        "mode": "gun",
        "type": "grpc"
      }
    }
  ]
}
